// AUTO-GENERATED by e2e/fixtures/generate.mjs — do not edit by hand.
export const EXPECTED = {
  "families": 4,
  "guests": 4,
  "devanagariName": "સુનીતા પટેલ",
  "leadingZeroPhone": "09876543213",
  "plus91Phone": "+919876543210",
  "rsvpFamilyU": 3,
  "rsvpAdults": 4,
  "rsvpChildren": 2
} as const
