/**
 * Generates the acceptance-test fixtures:
 *   e2e/fixtures/guests-test.xlsx  — a CALLING_MASTER_LIST-format workbook
 *   e2e/fixtures/expected.ts       — the exact expected row counts
 *   e2e/fixtures/proof-test.jpg    — an 800x600 JPEG for photo-proof tests
 *
 * The workbook deliberately includes the edge cases the acceptance suite
 * must survive (T0.10): a phone starting with 0, a +91 phone, a Devanagari
 * name, and a family with 4 adults + 2 children.
 *
 * Header row matches the app's known layout exactly (20 columns, blank name
 * header between SR.NO and PLACE — see src/lib/import/layout.ts).
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import * as XLSX from 'xlsx'

const OUT_DIR = join(process.cwd(), 'e2e', 'fixtures')

const HEADERS = [
  'U',
  'SR.NO',
  null, // Name column — blank header, located by position.
  'PLACE',
  'CONTACT',
  'ID',
  'Romm',
  'bed',
  'Pax',
  'Arrival Date',
  'Time',
  'Mode',
  'Details',
  'Pick up',
  'Remark',
  'Departure Date',
  'Time',
  'Mode',
  'Details',
  'Drop',
]

/**
 * The fixture data. Family 3 is the 4-adult / 2-child household the RSVP
 * tests target; family 2 has the Devanagari name; family 4 carries the
 * leading-zero phone; family 1 the +91 phone.
 */
const FAMILIES = [
  { u: 1, name: 'Rajesh Kumar', place: 'Ahmedabad', contact: '+919876543210', pax: 2, adults: 2, children: 0 },
  { u: 2, name: 'સુનીતા પટેલ', place: 'Vadodara', contact: '9876543211', pax: 2, adults: 2, children: 0 },
  { u: 3, name: 'Amit Shah', place: 'Surat', contact: '9876543212', pax: 6, adults: 4, children: 2 },
  { u: 4, name: 'Priya Mehta', place: 'Rajkot', contact: '09876543213', pax: 1, adults: 1, children: 0 },
]

const EXPECTED = {
  families: FAMILIES.length,
  // One head guest per family.
  guests: FAMILIES.length,
  // Known search targets.
  devanagariName: 'સુનીતા પટેલ',
  leadingZeroPhone: '09876543213',
  plus91Phone: '+919876543210',
  rsvpFamilyU: 3,
  rsvpAdults: 4,
  rsvpChildren: 2,
}

function rowFor(f) {
  return [
    f.u,
    f.u,
    f.name,
    f.place,
    f.contact,
    null, // ID
    null, // Romm
    null, // bed
    f.pax,
    '3', // Arrival Date — ordinal, resolves against the event window
    '10:30',
    'By Road',
    null,
    null,
    null,
    '8', // Departure Date — ordinal
    null,
    null,
    null,
    null,
  ]
}

function buildWorkbook() {
  const rows = [HEADERS, ...FAMILIES.map(rowFor)]
  const ws = XLSX.utils.aoa_to_sheet(rows)
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Sheet1')
  return wb
}

// A known-good 1x1 white JPEG, sufficient for upload/retrieval assertions.
const JPEG_B64 =
  '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a' +
  'HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAIAAAABAREA/8QAFAABAAAAAAAA' +
  'AAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAD8AVN//2Q=='

function main() {
  mkdirSync(OUT_DIR, { recursive: true })

  const wb = buildWorkbook()
  writeFileSync(join(OUT_DIR, 'guests-test.xlsx'), XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }))

  writeFileSync(join(OUT_DIR, 'proof-test.jpg'), Buffer.from(JPEG_B64, 'base64'))

  writeFileSync(
    join(OUT_DIR, 'expected.ts'),
    `// AUTO-GENERATED by e2e/fixtures/generate.mjs — do not edit by hand.\n` +
      `export const EXPECTED = ${JSON.stringify(EXPECTED, null, 2)} as const\n`,
  )

  console.log(
    `Wrote guests-test.xlsx (${EXPECTED.families} families, ${EXPECTED.guests} guests), proof-test.jpg, expected.ts`,
  )
}

main()
