'use client'

import { useRef, useState } from 'react'

import { UploadIcon } from '@/components/icons'
import { Button } from '@/components/ui/Button'
import { Card, CardBody } from '@/components/ui/Card'
import { parseImportFile, type ImportOutcome } from '@/lib/import/knownSheet'
import { KNOWN_SHEET_NAME } from '@/lib/import/parse'

export interface UploadStepProps {
  /** `events.starts_on`. Ordinal dates ("4TH") cannot resolve without it. */
  eventStartsOn: string | null
  /** `events.ends_on`. Nullable in the schema; the parser handles its absence. */
  eventEndsOn: string | null
  /** Called for both a clean parse and a layout mismatch — both are results. */
  onResult: (fileName: string, outcome: ImportOutcome) => void
  /** Called when the file could not be read at all (wrong tab, corrupt file). */
  onError: (message: string) => void
}

/**
 * Pick a file and parse it, entirely in this browser.
 *
 * The workbook is read with SheetJS from an ArrayBuffer and never uploaded.
 * 465 people's names and phone numbers do not need to cross the network for
 * somebody to look at a preview of them, so they do not.
 */
export function UploadStep({ eventStartsOn, eventEndsOn, onResult, onError }: UploadStepProps) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [busy, setBusy] = useState(false)

  async function handleFiles(files: FileList | null) {
    const file = files?.[0]
    if (!file) return

    setBusy(true)
    try {
      const outcome = await parseImportFile(file, {
        eventStartsOn,
        eventEndsOn,
      })
      onResult(file.name, outcome)
    } catch (e) {
      // `SheetNotFoundError` already carries a message naming the tabs that do
      // exist. Anything else is a genuinely unreadable file.
      onError(e instanceof Error ? e.message : 'Could not read that file.')
    } finally {
      setBusy(false)
      // Clearing the input matters: picking the SAME file twice after fixing a
      // cell fires no change event otherwise, and the screen looks frozen.
      if (inputRef.current) inputRef.current.value = ''
    }
  }

  return (
    <Card>
      <CardBody className="flex flex-col items-center gap-4 py-10 text-center">
        <span
          className="flex h-14 w-14 items-center justify-center rounded-full bg-tint-neutral text-muted"
          aria-hidden
        >
          <UploadIcon className="h-7 w-7" />
        </span>

        <div>
          <p className="text-base font-semibold text-fg">Choose the calling list</p>
          <p className="mt-1 text-sm text-muted">
            .xlsx or .xls. A full CALLING MASTER LIST (the{' '}
            <span className="font-medium text-fg">{KNOWN_SHEET_NAME}</span> tab) is read in full —
            travel, rooms, pax. A plain list with just{' '}
            <span className="font-medium text-fg">Name</span> and{' '}
            <span className="font-medium text-fg">Contact</span> columns works too — each row
            becomes one guest to call.
          </p>
          <p className="mt-1 text-sm text-muted">
            The file is read on this phone and is not uploaded anywhere.
          </p>
        </div>

        <input
          ref={inputRef}
          type="file"
          // Broad accept on purpose: Android's document picker matches MIME
          // types, not bare extensions, and with ".xlsx,.xls" alone it can
          // offer no spreadsheet apps at all. The MIME types cover the
          // realistic set; the parser still rejects anything it can't read.
          accept=".xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel"
          className="sr-only"
          onChange={(e) => handleFiles(e.target.files)}
          disabled={busy}
        />
        <Button type="button" size="lg" loading={busy} onClick={() => inputRef.current?.click()}>
          {busy ? 'Reading file…' : 'Choose file'}
        </Button>

        {/* The template is the cheapest fix for the most expensive failure.
            Column resolution is EXACT-MATCH ONLY — deliberately, because a
            fuzzily-matched header gives every family someone else's phone
            number and nobody can see it happened. The cost of that strictness
            is that a sheet built from imagination fails, and by then the
            person has already typed 200 rows. Handing them the headers BEFORE
            they start inverts that. Generated by
            scripts/make-import-template.mjs; it round-trips through this very
            parser with zero warnings, which is a test worth keeping true. */}
        <a
          href="/nuvent-guest-list-template.xlsx"
          download
          className="text-sm font-medium text-brand underline underline-offset-2"
        >
          Download the blank template
        </a>
        <p className="-mt-2 text-xs leading-relaxed text-subtle">
          Building the sheet from scratch? Start here. The column headers have to
          match exactly, and the template already has them right.
        </p>
      </CardBody>
    </Card>
  )
}

export default UploadStep
