import type { Metadata, Viewport } from 'next'
import {
  Bricolage_Grotesque,
  Figtree,
  IBM_Plex_Mono,
  IBM_Plex_Sans_Devanagari,
} from 'next/font/google'
import type { ReactNode } from 'react'

import { MotionProvider } from '@/components/motion/MotionProvider'
import { QueryProvider } from '@/components/providers/QueryProvider'
import { WelcomeOverlay } from '@/components/motion/WelcomeOverlay'
import { MobileViewport } from '@/components/native/MobileViewport'
import { NativeBridge } from '@/components/native/NativeBridge'
import { SessionBridge } from '@/components/native/SessionBridge'
import { OfflineBanner } from '@/components/native/OfflineBanner'
import { SentryErrorBoundary } from '@/components/native/SentryErrorBoundary'
import { initSentry } from '@/lib/sentry'
import { getUiVersion } from '@/lib/ui-version'
import { V2_OFFLINE_NOTE } from '@/lib/offline-note'
import { wireExternalLinkInterception } from '@/lib/native/navigation'

import './globals.css'

// Install Sentry global handlers on the client before anything renders.
if (typeof window !== 'undefined') {
  initSentry()
  // tel:/mailto: links belong to the OS, not the WebView — a captured click
  // on one must go to the system dialer and never navigate the WebView (the
  // Tier-0 call bug). This wires the document-level interceptor once.
  wireExternalLinkInterception()
}

/**
 * The four faces of the v3 design, self-hosted.
 *
 * `next/font/google` downloads and fingerprints these at BUILD time and
 * serves them from our own origin, so the venue's Wi-Fi is never in the
 * critical path — a `<link>` to fonts.googleapis.com would leave staff
 * staring at fallback metrics (or nothing) exactly when the network is
 * worst. It also inlines the font-face metrics, so there is no layout
 * shift when they land.
 *
 * `display: 'swap'` on all four: fallback text immediately, never a flash
 * of invisible text.
 */

/**
 * Display — screen titles, big numbers, the Now-card headline. Nothing
 * else. The variable axis is requested (Bricolage Grotesque is a variable
 * face) with the two weights the spec names: 600 for titles, 700 for the
 * Now-card headline.
 */
const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-bricolage',
  display: 'swap',
})

/**
 * Body — every row, label, button and paragraph. 400 for body, 500/600 for
 * emphasis and labels, 700 for the rare bold. Nothing else is loaded: each
 * extra weight is another file over venue Wi-Fi.
 */
const figtree = Figtree({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-figtree',
  display: 'swap',
})

/**
 * The Devanagari cut. Family names come off the Excel sheet in Hindi
 * ("शर्मा परिवार") and sit inline with Latin on the same row — without
 * this they fall back to whatever the Android WebView happens to ship,
 * which is a different weight and a different x-height on every handset.
 */
const plexDevanagari = IBM_Plex_Sans_Devanagari({
  subsets: ['devanagari', 'latin'],
  weight: ['400', '500', '600'],
  variable: '--font-plex-devanagari',
  display: 'swap',
})

/** Every figure in the app, plus every phone and flight number. */
const plexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-plex-mono',
  display: 'swap',
})

/**
 * Be Vietnam Pro is gone with the gold. v3 puts Bricolage Grotesque on the
 * display tier and Figtree on the body tier, so shipping a third Latin
 * family nothing references is a font file downloaded for no reason. The
 * Devanagari cut and the mono stay: both are load-bearing (see the token
 * comments in globals.css).
 */
const fontVariables = [
  bricolage.variable,
  figtree.variable,
  plexDevanagari.variable,
  plexMono.variable,
].join(' ')

export const metadata: Metadata = {
  title: {
    default: 'EventFlow',
    template: '%s · EventFlow',
  },
  description:
    'Wedding event operations — guest groups, RSVP calling, rooms, hampers and logistics.',
  applicationName: 'EventFlow',
  // src/app/manifest.ts. Named explicitly because the APK's WebView and any
  // "add to home screen" both need the <link rel="manifest"> tag emitted.
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    title: 'EventFlow',
    statusBarStyle: 'default',
  },
  // icon / apple-icon / favicon.ico are picked up from the App Router file
  // conventions in this directory (src/app/icon.png, apple-icon.png,
  // favicon.ico) — all three generated by scripts/brand-assets.mjs. Declaring
  // them here as well would emit duplicate <link> tags.
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // The APK draws under the notch and the gesture bar; the `*-safe`
  // utilities in globals.css depend on this.
  viewportFit: 'cover',
  // Android Chrome shrinks the layout viewport when the keyboard opens unless
  // told otherwise — that reads as the whole page zooming on every tap into a
  // field. Staff forms are the whole app; keep the shell stable.
  interactiveWidget: 'resizes-content',
  // One colour, both media: the staff app does not follow the OS, so the
  // system chrome must not either. A dark status bar over the paper ground
  // is the tell that the two disagree. v3 paper, kept in step with
  // `--ef-paper` in globals.css.
  themeColor: '#f7f3ec',
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  /**
   * ONE offline banner, on every route, owned by this layout.
   *
   * This used to be `getUiVersion() !== 'v2'` while the v2 shell rendered its
   * own banner with an extra training line. That fixed a double banner and broke
   * the routes the v2 shell does not cover — `/login`, `/pick-staff` and
   * `/admin/**` lost the banner entirely under v2, and the sign-in screen is
   * exactly where a staff member with no signal is most likely to be. Found by
   * the R1 review, not by a test.
   *
   * So the banner is always rendered here and only its NOTE depends on the flag:
   * v1 passes nothing and its output is unchanged, v2 adds the line from
   * CLAUDE.md §11b. Read through `getUiVersion()`, the same helper `src/proxy.ts`
   * gates the rewrite on, in a SERVER component so it resolves at request time
   * and cannot disagree with the router.
   */
  const offlineNote = getUiVersion() === 'v2' ? V2_OFFLINE_NOTE : undefined

  return (
    // suppressHydrationWarning: the Android WebView injects a style
    // attribute with --safe-area-inset-* vars onto <html> (viewport-fit
    // cover) before React hydrates. The server cannot know those values, so
    // we let React keep the WebView's version instead of erroring.
    <html lang="en" className={`h-full ${fontVariables}`} suppressHydrationWarning>
      <body className="min-h-dvh bg-paper font-sans text-base text-ink antialiased">
        <SentryErrorBoundary>
          <SessionBridge />
          <MobileViewport />
          <NativeBridge />
          {/* OtaUpdater temporarily removed — @capgo/capacitor-updater's
              native init calls Capacitor core's notifyListeners(..., true),
              which throws in Capacitor 8 and blanks the WebView. Restore once
              the core/capgo versions align. */}
          {<OfflineBanner offlineNote={offlineNote} />}
          {/* MotionProvider renders no DOM — it supplies the LazyMotion and
              MotionConfig context (OS reduced-motion, the house easing) and
              code-splits the feature bundle off the initial route. It wraps
              WelcomeOverlay because the overlay uses `m` components, and
              wraps `children` so screens can animate without each one
              re-establishing the context. */}
          <MotionProvider>
            <WelcomeOverlay />
            {/* QueryProvider, not QueryClientProvider directly: this file is a
                server component and a QueryClient cannot cross that boundary
                as a prop. See the note in QueryProvider.tsx. */}
            <QueryProvider>{children}</QueryProvider>
          </MotionProvider>
        </SentryErrorBoundary>
      </body>
    </html>
  )
}
